Repository DufourVictor/intranet_nodevo_front, pull requests merged in 2018-03, with the labels that each got.

#3 Add login form base
  src/app/app.module.ts
  src/app/authentification.service.ts
  src/app/login/login.component.html
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/token.interceptor.ts
Labels: Développement, Front

#5 Dashboard and redirect form login
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.scss
  src/app/dashboard/dashboard.component.ts
  src/app/login/login.component.ts
Labels: Développement, Front

#17 Add toggle enabled on user list + fix require error
  package-lock.json
  package.json
  src/app/authentification.service.ts
  src/app/users/users.component.ts
  src/tsconfig.app.json
Labels: Développement, bug

#16 Add spectre modal component generic
  src/app/app.module.ts
  src/app/spectre-modal/spectre-modal.component.html
  src/app/spectre-modal/spectre-modal.component.scss
  src/app/spectre-modal/spectre-modal.component.ts
  src/app/users/users.component.ts
Labels: enhancement

#18 Add user form
  src/_form.scss
  src/_variables.scss
  src/app/app-routing.module.ts
  src/app/user-form/user-form.component.html
  src/app/user-form/user-form.component.ts
  src/app/users/users.component.html
  src/backend/forms/UserValidators.ts
  src/backend/forms/tools/Form.service.ts
  src/backend/model/User.ts
  src/styles.scss
Labels: Développement, Intégration

#36 Add sidebar style
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/login/login.component.scss
  src/app/menu/menu.component.html
  src/app/menu/menu.component.scss
  src/assets/bg_login.jpg
  src/assets/colors.scss
  src/assets/logo_nodevo.png
  src/assets/logo_nodevo_mini.png
  src/styles.scss
  src/styles/_form.scss
  src/styles/_mixins.scss
  src/styles/_sidebar.scss
  src/styles/_variables.scss
Labels: Front

#38 List customers + Active/unactive + Delete flag
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/business/business.component.ts
  src/app/customers/customers.component.html
  src/app/customers/customers.component.scss
  src/app/customers/customers.component.ts
  src/app/empowerment/empowerment.component.ts
  src/app/menu/menu.component.html
  src/app/user/users.component.ts
  src/backend/forms/base-form-validators/CustomerValidatorsBase.ts
  src/backend/model/Contact.ts
  src/backend/model/Customer.ts
  src/backend/model/Type.ts
  src/backend/model/base/CustomerBase.ts
Labels: Développement, Front

#42 Correction bug merge
  src/app/business/business.component.ts
Labels: Développement
